### PR TITLE
Upgrade bugsnag library from v2 to v3

### PR DESCRIPTION
**Pull request by ffffranklin**
https://github.com/bugsnag/bugsnag-js/releases/tag/v3.0.0

> This release adds support for automatic and custom breadcrumb tracking.   Breadcrumbs replace the private implementation of "last event" tracking.  It also removes support for the deprecated userId setting, which has been replaced by the user object.

### CODE REVIEW

**Comment by eanakashima** [comment]
Thanks @ffffranklin!

**Comment by ffffranklin** [comment]
:bump: @ndhoule @hankim813

**Comment by hankim813** [comment]
@ffffranklin thanks for the PR! I'm good with this update as long as there are no breaking changes in integration behavior. If all the changes are augmentative we're all set. Just want to make sure that the code we are using will not break/create unexpected behavior in data customers see inside Bugsnag.

**Comment by eanakashima** [comment]
> Just want to make sure that the code we are using will not break/create unexpected behavior in data customers see inside Bugsnag.

I can provide a bit more detail here. The configuration API and browser support are the same in 3.x as in 2.x, so this change shouldn't break any existing customers' Bugsnag integrations. The biggest difference between the 2.x and 3.x releases of the notifier is the addition of [automatic breadcrumb tracking](https://blog.bugsnag.com/javascript-automatic-breadcrumbs/), so customers will see some new data in their dashboards that should help make it easier to figure out the user actions that lead up to a particular js error. Check out our [release notes](https://github.com/bugsnag/bugsnag-js/releases) in the bugsnag/bugsnag-js repo if you want all the details. Thanks!

**Comment by hankim813** [comment]
@eanakashima Awesome! Great feature :)

I'll be sure to include this in the next update to `analytics.js`! (Should be this week! Tomorrow most likely)

**Comment by ffffranklin** [comment]
@hankim813 any update on this?

**Comment by hankim813** [comment]
@ffffranklin deployed!

**Comment by eanakashima** [comment]
Thanks!

**Pull request merged**
