### PR TITLE
Make use of the user object

### PR DESCRIPTION
**Pull request by nblackburn**
Make use of the user object so user information shows up in the user tab.

**Details**: https://bugsnag.com/docs/notifiers/js/#user

### CODE REVIEW

**Comment by WesleyDRobinson** [comment]
Docs on metadata and user object:
https://bugsnag.com/docs/notifiers/js/#user

**Comment by nblackburn** [comment]
@WesleyDRobinson Whoops, thanks for reminding me to include this :smile:

**Comment by f2prateek** [comment]
LGTM

**Comment by f2prateek** [comment]
Thanks!

**Pull request merged**
